services:
  db:
    image: postgres:15
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: syntax_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata2509:/var/lib/postgresql/data

volumes:
  pgdata2509: